# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn and Install dependencies
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt update && sudo apt install yarn
        yarn install
  
    - name: Build
      run : |
        yarn docs:build

    - name: Publish to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: tsunematsu21/actions-publish-gh-pages@c04b531c52b8f9d25c596bc6e6a7ddc116b2f3f8
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
        # The name of the directory that containing the content to be published
        dir: ./dist
        # The name of the remote branch that publishing source for GitHub Pages site
        branch: master
        # The remote repository that publishing source for GitHub Pages site, defaults to current repo and is formatted like 'user/repo-name'
        repo: xiao-gy.github.io
        # The personal access token that authorize repo access
        token: ${{ secrets.publish }}
